.MODEL SMALL
.STACK 100H
.DATA
    NICKNAME DB 5 DUP(?), '$'
    NEWLINE DB 0Dh, 0Ah, '$'
.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX

    MOV CX, 5
    LEA SI, NICKNAME
INPUT_LOOP:
    MOV AH, 1
    INT 21H
    MOV [SI], AL
    INC SI
    LOOP INPUT_LOOP

    LEA SI, NICKNAME
    MOV CX, 5
CONVERT_LOOP:
    MOV AL, [SI]
    CMP AL, 'A'
    JL NO_CONVERSION
    CMP AL, 'Z'
    JG NO_CONVERSION
    ADD AL, 32
NO_CONVERSION:
    MOV [SI], AL
    INC SI
    LOOP CONVERT_LOOP

    LEA DX, NEWLINE
    MOV AH, 9
    INT 21H

    LEA DX, NICKNAME
    MOV AH, 9
    INT 21H

    MOV AH, 4CH
    INT 21H
MAIN ENDP
END MAIN
